#!/usr/bin/env bash
# project-context.sh: read-only snapshot of a project for the squad.
# Prints Markdown covering the git baseline, agent/contributor instructions,
# custom agents, stack, commands, design system, i18n, tests and CI.
#
# Usage: bash project-context.sh [project-dir]   (default: git root of the current dir)
# Never modifies anything. Never prints the contents of .env files.

set -u

START="${1:-.}"
cd "$START" 2>/dev/null || { echo "error: cannot cd to $START" >&2; exit 1; }
ROOT=$(git rev-parse --show-toplevel 2>/dev/null || pwd)
cd "$ROOT" || exit 1

have() { command -v "$1" >/dev/null 2>&1; }

# find, skipping vendored, generated and heavy folders.
# Usage: find_src <maxdepth> <find predicates...>
find_src() {
  local depth=$1
  shift
  find . -maxdepth "$depth" \
    \( -name node_modules -o -name .git -o -name dist -o -name build -o -name .next \
       -o -name .expo -o -name .turbo -o -name .cache -o -name coverage -o -name vendor \
       -o -name Pods -o -name .gradle -o -name .venv -o -name venv -o -name __pycache__ \
       -o -name target -o -name .squad -o -name DerivedData -o -name .svelte-kit \) -prune \
    -o \( "$@" \) -print 2>/dev/null | sed 's#^\./##' | sort
}

# Print up to N lines of stdin as a bullet list, then "(+k more)".
bullets() {
  local max=$1 n=0 line
  while IFS= read -r line; do
    [ -z "$line" ] && continue
    n=$((n + 1))
    [ "$n" -le "$max" ] && echo "- $line"
  done
  [ "$n" -gt "$max" ] && echo "- (+$((n - max)) more)"
  return 0
}

# Read a field from package.json. Usage: pkg <file> scripts|deps|pm
pkg() {
  if have node; then
    node -e '
      const p = JSON.parse(require("fs").readFileSync(process.argv[1], "utf8"));
      const what = process.argv[2];
      if (what === "scripts") for (const [k, v] of Object.entries(p.scripts || {})) console.log(k + "\t" + v);
      if (what === "deps") console.log(Object.keys(Object.assign({}, p.dependencies, p.devDependencies, p.peerDependencies)).join("\n"));
      if (what === "pm" && p.packageManager) console.log(p.packageManager.split("@")[0]);
    ' "$1" "$2" 2>/dev/null
  elif have python3; then
    python3 - "$1" "$2" <<'PY' 2>/dev/null
import json, sys
p = json.load(open(sys.argv[1], encoding="utf-8"))
what = sys.argv[2]
if what == "scripts":
    for k, v in (p.get("scripts") or {}).items():
        print(f"{k}\t{v}")
elif what == "deps":
    d = {}
    for key in ("dependencies", "devDependencies", "peerDependencies"):
        d.update(p.get(key) or {})
    print("\n".join(d))
elif what == "pm" and p.get("packageManager"):
    print(p["packageManager"].split("@")[0])
PY
  elif have jq; then
    case "$2" in
      scripts) jq -r '.scripts // {} | to_entries[] | "\(.key)\t\(.value)"' "$1" ;;
      deps) jq -r '[.dependencies, .devDependencies, .peerDependencies] | map(. // {} | keys) | add | .[]' "$1" ;;
      pm) jq -r '.packageManager // empty | split("@")[0]' "$1" ;;
    esac 2>/dev/null
  fi
}

echo "## Project snapshot"
echo
echo "_Generated by squad/scripts/project-context.sh on $(date '+%Y-%m-%d %H:%M')._"
echo
echo "- **Root:** \`$ROOT\`"

# ---------------------------------------------------------------- git
echo
echo "### Git baseline"
echo
if git rev-parse --git-dir >/dev/null 2>&1; then
  branch=$(git branch --show-current 2>/dev/null)
  default=$(git symbolic-ref --quiet --short refs/remotes/origin/HEAD 2>/dev/null | sed 's#^origin/##')
  echo "- **Branch:** \`${branch:-detached}\`${default:+ (default: \`$default\`)}"
  if git rev-parse --verify --quiet HEAD >/dev/null; then
    echo "- **Base commit:** \`$(git rev-parse HEAD)\`, $(git log -1 --format='%s' | cut -c1-80)"
  else
    echo "- **Base commit:** none (no commits yet)"
  fi
  changes=$(git status --porcelain --untracked-files=all 2>/dev/null | grep -v ' \.squad/' || true)
  if [ -n "$changes" ]; then
    echo "- **Already modified before the squad started** ($(printf '%s\n' "$changes" | wc -l | tr -d ' ') files; leave them alone and keep them out of reviews):"
    printf '%s\n' "$changes" | sed 's/^/`/; s/$/`/' | bullets 40 | sed 's/^/  /'
  else
    echo "- **Working tree:** clean"
  fi
  echo "- **Recent commits:**"
  git log -5 --format='  - `%h` %s' 2>/dev/null
else
  echo "- Not a git repository: there is no base commit to diff against. Reviewers must rely on the dev notes and file timestamps."
fi

# ------------------------------------------------- instructions & agents
echo
echo "### Agent and contributor instructions (every role should read these)"
echo
found=$(
  for f in CLAUDE.md CLAUDE.local.md .claude/CLAUDE.md AGENTS.md GEMINI.md .cursorrules .windsurfrules \
           .github/copilot-instructions.md CONTRIBUTING.md docs/CONTRIBUTING.md; do
    [ -f "$f" ] && echo "\`$f\` ($(wc -l <"$f" | tr -d ' ') lines)"
  done
  [ -d .cursor/rules ] && echo "\`.cursor/rules/\` ($(find .cursor/rules -type f | wc -l | tr -d ' ') files)"
  find_src 4 -type f \( -name CLAUDE.md -o -name AGENTS.md \) | grep / | grep -v '^\.claude/CLAUDE.md$' | sed 's/^/`/; s/$/` (nested)/'
)
if [ -n "$found" ]; then printf '%s\n' "$found" | bullets 20; else echo "- none found"; fi

agents=$(find .claude/agents .opencode/agent .opencode/agents -maxdepth 1 -name '*.md' 2>/dev/null | sort)
if [ -n "$agents" ]; then
  echo
  echo "**Custom agents in this project** (use them for matching roles):"
  printf '%s\n' "$agents" | sed 's/^/`/; s/$/`/' | bullets 20
fi
skills=$(find .claude/skills .agents/skills -mindepth 2 -maxdepth 2 -name SKILL.md 2>/dev/null | sort)
if [ -n "$skills" ]; then
  echo
  echo "**Project skills:**"
  printf '%s\n' "$skills" | sed 's#/SKILL.md$##; s/^/`/; s/$/`/' | bullets 20
fi

# ---------------------------------------------------------------- stack
echo
echo "### Stack"
echo
stack=""
add() { stack="$stack$1"$'\n'; }

pm=""
if [ -f package.json ]; then
  if [ -f pnpm-lock.yaml ]; then pm=pnpm
  elif [ -f bun.lockb ] || [ -f bun.lock ]; then pm=bun
  elif [ -f yarn.lock ]; then pm=yarn
  elif [ -f package-lock.json ]; then pm=npm
  else pm=$(pkg package.json pm); pm=${pm:-npm}
  fi
  add "JavaScript/TypeScript, package manager **$pm**"
fi
mono=""
for f in pnpm-workspace.yaml turbo.json nx.json lerna.json; do [ -f "$f" ] && mono="$mono \`$f\`"; done
[ -f package.json ] && grep -q '"workspaces"' package.json && mono="$mono \`package.json#workspaces\`"
[ -n "$mono" ] && add "Monorepo:$mono"
[ -f deno.json ] || [ -f deno.jsonc ] && add "Deno (\`deno task\`, \`deno test\`)"
if [ -f pyproject.toml ] || [ -f requirements.txt ] || [ -f Pipfile ] || [ -f setup.py ]; then
  py="Python"
  [ -f uv.lock ] && py="$py (uv)"
  [ -f poetry.lock ] && py="$py (poetry)"
  tools=$(cat pyproject.toml requirements*.txt Pipfile setup.cfg 2>/dev/null \
    | grep -oiE '\b(django|fastapi|flask|sqlalchemy|alembic|pydantic|pytest|ruff|mypy|pyright|black|flake8|celery)\b' \
    | tr '[:upper:]' '[:lower:]' | sort -u | tr '\n' ' ')
  add "$py${tools:+: $tools}"
fi
[ -f go.mod ] && add "Go (\`go test ./...\`, \`go vet ./...\`)"
[ -f Cargo.toml ] && add "Rust (\`cargo test\`, \`cargo clippy\`)"
[ -f Gemfile ] && add "Ruby$(grep -qE "^[[:space:]]*gem ['\"]rails['\"]" Gemfile && echo ' on Rails') (bundle exec ...)"
[ -f composer.json ] && add "PHP (composer)"
[ -f pom.xml ] && add "Java/Kotlin (Maven)"
{ [ -f build.gradle ] || [ -f build.gradle.kts ]; } && add "Java/Kotlin (Gradle)"
[ -f Package.swift ] && add "Swift package (\`swift test\`)"
xc=$(find . -maxdepth 2 -name '*.xcodeproj' -not -path './ios/*' 2>/dev/null | head -1)
[ -n "$xc" ] && add "Xcode project \`${xc#./}\`"
[ -f pubspec.yaml ] && add "Flutter/Dart (\`flutter test\`, \`dart analyze\`)"
[ -f mix.exs ] && add "Elixir (\`mix test\`)"
{ [ -f app.json ] && grep -q '"expo"' app.json; } || [ -f app.config.js ] || [ -f app.config.ts ] && add "Expo app (config: $(ls app.json app.config.* 2>/dev/null | tr '\n' ' ' | sed 's/ $//'))"
[ -f eas.json ] && add "EAS (\`eas.json\`)"
{ [ -f Dockerfile ] || [ -f docker-compose.yml ] || [ -f compose.yaml ] || [ -f docker-compose.yaml ]; } && add "Docker ($(ls Dockerfile docker-compose.yml docker-compose.yaml compose.yaml 2>/dev/null | tr '\n' ' ' | sed 's/ $//'))"
if [ -n "$stack" ]; then printf '%s' "$stack" | bullets 20; else echo "- not detected; look at the root files"; fi

# Notable JS dependencies across the root and workspace packages.
if [ -f package.json ]; then
  pkgs=$(find_src 4 -name package.json -type f | head -40)
  deps=$(for p in $pkgs; do pkg "$p" deps; done | sort -u)
  notable=$(printf '%s\n' "$deps" | grep -E '^(next|nuxt|react|react-native|expo|expo-router|vue|svelte|@sveltejs/kit|@angular/core|@remix-run/.*|astro|solid-js|electron|@tauri-apps/api|express|fastify|@nestjs/core|hono|koa|prisma|@prisma/client|drizzle-orm|typeorm|sequelize|mongoose|@supabase/supabase-js|firebase|@react-native-firebase/app|@tanstack/react-query|swr|@apollo/client|@trpc/server|zustand|@reduxjs/toolkit|mobx|jotai|tailwindcss|nativewind|styled-components|@emotion/react|@mui/material|@chakra-ui/react|@mantine/core|antd|tamagui|@shopify/restyle|react-native-unistyles|@radix-ui/.*|lucide-react|@expo/ui|react-native-reanimated|i18next|react-i18next|next-intl|react-intl|expo-localization|@lingui/core|jest|jest-expo|vitest|@playwright/test|cypress|@testing-library/.*|detox|mocha|@storybook/.*|msw|supertest|typescript|eslint|@biomejs/biome|prettier|oxlint|react-native-purchases|@sentry/.*|posthog-.*|@amplitude/.*|mixpanel-.*)$' \
    | sed -E 's#^(@radix-ui|@storybook|@sentry|@remix-run|@amplitude)/.*#\1/*#' | sort -u | tr '\n' ' ')
  [ -n "$notable" ] && echo "- **Notable dependencies:** $notable"
  [ "$(printf '%s\n' "$pkgs" | grep -c .)" -gt 1 ] && {
    echo "- **package.json files:**"
    printf '%s\n' "$pkgs" | sed 's/^/`/; s/$/`/' | bullets 15 | sed 's/^/  /'
  }
fi

# -------------------------------------------------------------- commands
echo
echo "### Commands"
echo
commands=$(
if [ -f package.json ]; then
  run="$pm run"
  [ "$pm" = yarn ] && run="yarn"
  [ "$pm" = bun ] && run="bun run"
  scripts=$(pkg package.json scripts)
  if [ -n "$scripts" ]; then
    echo "**package.json scripts** (run with \`$run <name>\`):"
    echo
    printf '%s\n' "$scripts" | while IFS="$(printf '\t')" read -r name cmd; do
      echo "- \`$name\`: \`$(printf '%s' "$cmd" | cut -c1-100)\`"
    done | head -40
    names=$(printf '%s\n' "$scripts" | cut -f1)
    missing=""
    for check in lint typecheck test build; do
      re="^$check\$"
      [ "$check" = test ] && re='^test(:unit)?$'
      [ "$check" = typecheck ] && re='^(typecheck|type-check|types|tsc|check-types|check)$|:types$|:typecheck$'
      printf '%s\n' "$names" | grep -qE "$re" || missing="$missing $check"
    done
    [ -n "$missing" ] && { echo; echo "**No script for:**$missing. Don't go looking for these; report them as n/a."; }
  else
    echo "- package.json has no scripts"
  fi
fi
for mk in Makefile makefile GNUmakefile; do
  if [ -f "$mk" ]; then
    targets=$(grep -E '^[A-Za-z0-9][A-Za-z0-9_.-]*:([^=]|$)' "$mk" | cut -d: -f1 | sort -u | tr '\n' ' ')
    [ -n "$targets" ] && { echo; echo "**$mk targets:** $targets"; }
    break
  fi
done
if [ -f justfile ] || [ -f Justfile ]; then
  jf=$(ls justfile Justfile 2>/dev/null | head -1)
  recipes=$(grep -E '^[A-Za-z0-9_-]+( [^:=]*)?:' "$jf" | cut -d: -f1 | awk '{print $1}' | sort -u | tr '\n' ' ')
  [ -n "$recipes" ] && { echo; echo "**justfile recipes:** $recipes"; }
fi
[ -f Taskfile.yml ] && { echo; echo "**Taskfile.yml** present (\`task --list\`)."; }
bins=$(find scripts bin -maxdepth 1 -type f 2>/dev/null | sort | head -15 | sed 's/^/`/; s/$/`/' | tr '\n' ' ')
[ -n "$bins" ] && { echo; echo "**Repo scripts:** $bins"; }
)
if [ -n "$commands" ]; then printf '%s\n' "$commands" | sed '/./,$!d'; else echo "- none detected; check the README and CI config for how to build and test"; fi

# ------------------------------------------------------------ UI & i18n
echo
echo "### UI and design system"
echo
ui=$(
  [ -f components.json ] && echo "shadcn/ui (\`components.json\`)"
  ls tailwind.config.* 2>/dev/null | sed 's/^/`/; s/$/`/'
  [ -d .storybook ] && echo "Storybook (\`.storybook/\`)"
  find_src 5 -type d \( -name components -o -name ui -o -name design-system -o -name primitives \) | grep -vE '(^|/)(ios|android)/' | head -12 | sed 's/^/component dir: `/; s/$/`/'
  find_src 6 -type f \( -iname 'theme.*' -o -iname 'tokens.*' -o -iname '*.tokens.json' -o -iname 'colors.*' -o -iname 'typography.*' -o -iname 'spacing.*' \) | grep -vE '\.(png|jpg|svg)$' | head -12 | sed 's/^/tokens\/theme: `/; s/$/`/'
  find_src 4 -type f -name 'globals.css' | head -3 | sed 's/^/global styles: `/; s/$/`/'
  find_src 3 -type f \( -name '*.html' -o -name '*.htm' \) | grep -vE '(^|/)(coverage|docs?|test|tests|e2e)/' | head -8 | sed 's/^/HTML page: `/; s/$/`/'
  find_src 3 -type d \( -name templates -o -name views -o -name screens -o -name pages -o -name app -o -name routes \) | grep -vE '(^|/)(ios|android|node_modules)/' | head -8 | sed 's/^/screens\/routes: `/; s/$/`/'
)
if [ -n "$ui" ]; then printf '%s\n' "$ui" | bullets 30; else echo "- no UI layer detected"; fi
i18n=$(find_src 4 -type d \( -name locales -o -name i18n -o -name translations -o -name lang -o -name messages \) | head -6)
[ -n "$i18n" ] && { echo; echo "**i18n folders:** $(printf '%s\n' "$i18n" | sed 's/^/`/; s/$/`/' | tr '\n' ' ')"; }

# ----------------------------------------------------------------- tests
echo
echo "### Tests"
echo
tconf=$(ls jest.config.* vitest.config.* vitest.workspace.* playwright.config.* cypress.config.* \
  pytest.ini conftest.py .detoxrc* karma.conf.* phpunit.xml* .rspec 2>/dev/null | tr '\n' ' ')
[ -n "$tconf" ] && echo "- **Config:** $tconf"
tdirs=$(find_src 3 -type d \( -name e2e -o -name tests -o -name test -o -name __tests__ -o -name spec -o -name cypress -o -name .maestro \) | head -10 | tr '\n' ' ')
[ -n "$tdirs" ] && echo "- **Test folders:** $tdirs"
tfiles=$(find_src 8 -type f \( -name '*.test.*' -o -name '*.spec.*' -o -name 'test_*.py' -o -name '*_test.py' -o -name '*_test.go' -o -name '*Tests.swift' -o -name '*Test.kt' -o -name '*_spec.rb' \))
tcount=$(printf '%s\n' "$tfiles" | grep -c . || true)
if [ "$tcount" -gt 0 ]; then
  echo "- **Test files:** $tcount, e.g. $(printf '%s\n' "$tfiles" | head -4 | sed 's/^/`/; s/$/`/' | tr '\n' ' ')"
else
  echo "- **Test files:** none found. Dev and QA should say how they verified the change without automated tests."
fi

# ------------------------------------------------------------ CI & env
echo
echo "### CI, env and docs"
echo
ci=$(ls .github/workflows/*.yml .github/workflows/*.yaml .gitlab-ci.yml .circleci/config.yml bitbucket-pipelines.yml azure-pipelines.yml 2>/dev/null | tr '\n' ' ')
echo "- **CI:** ${ci:-none found}"
envs=$(ls .env.example .env.sample .env.template .env.local.example 2>/dev/null | tr '\n' ' ')
[ -n "$envs" ] && echo "- **Env templates:** $envs"
ls .env .env.local >/dev/null 2>&1 && echo "- A local \`.env\` exists. Never print, copy or commit its contents."
docs=$(find_src 3 -type d \( -iname adr -o -iname adrs -o -iname decisions -o -iname specs -o -iname rfcs -o -iname prd \) | tr '\n' ' ')
[ -d docs ] && echo "- **docs/:** $(find docs -maxdepth 1 -mindepth 1 | wc -l | tr -d ' ') entries"
[ -n "$docs" ] && echo "- **Specs/decisions folders:** $docs"
echo
exit 0
